from scripts.model.custom_torch_model import CustomFCNet
from scripts.model.model_inferece import InferenceModel
from scripts.model.action_dists_inferece import InferenceBetaDist
from scripts.model.action_dists import TorchBetaTest_blue, TorchBetaTest_yellow